"use client";

import React, { useState } from "react";
import toast from "react-hot-toast";
import { api } from "@/lib/api";
import { CheckCircle2, AlertTriangle, RefreshCw } from "lucide-react";

interface Props {
  jobDescriptionId: number;
}

export function AptitudeTest({ jobDescriptionId }: Props) {
  const [questions, setQuestions] = useState<any[]>([]);
  const [answers, setAnswers] = useState<{[key: number]: string}>({});
  const [generating, setGenerating] = useState(false);
  const [score, setScore] = useState<number | null>(null);

  const handleGenerate = async () => {
    if (!jobDescriptionId) {
      toast.error("Please analyze a job description first.");
      return;
    }
    setGenerating(true);
    setScore(null);
    setAnswers({});
    try {
      const res = await api.post("/assessments/aptitude/generate", {
        job_description_id: jobDescriptionId
      });
      setQuestions(res.questions || []);
      toast.success("Aptitude test generated successfully!");
    } catch (err: any) {
      toast.error("Failed to generate test: " + err.message);
    } finally {
      setGenerating(false);
    }
  };

  const handleSubmit = () => {
    if (Object.keys(answers).length < questions.length) {
      toast.error("Please answer all questions before submitting.");
      return;
    }
    let correctCount = 0;
    questions.forEach((q, idx) => {
      if (answers[idx] === q.correct_answer) {
        correctCount++;
      }
    });
    setScore((correctCount / questions.length) * 100);
  };

  return (
    <div className="glass-panel p-6 rounded-2xl space-y-6">
      <div>
        <h4 className="font-bold text-base text-amber-400">Aptitude & Logical Reasoning</h4>
        <p className="text-xs text-zinc-500 mt-1">Practice role-specific logic questions generated by AI.</p>
      </div>

      {questions.length === 0 ? (
        <div className="text-center py-12">
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="bg-gradient-to-r from-amber-600 to-yellow-500 hover:from-amber-500 hover:to-yellow-400 text-white font-bold py-3 px-8 rounded-xl text-sm transition active:scale-[0.98] shadow-lg shadow-amber-900/20 disabled:opacity-50"
          >
            {generating ? (
              <span className="flex items-center gap-2"><RefreshCw className="animate-spin" size={16}/> Generating Test...</span>
            ) : "Generate Practice Test"}
          </button>
        </div>
      ) : (
        <div className="space-y-8">
          {questions.map((q, idx) => (
            <div key={idx} className="glass-card p-6 rounded-xl space-y-4">
              <p className="font-medium text-white">{idx + 1}. {q.question}</p>
              <div className="space-y-2">
                {q.options.map((opt: string, optIdx: number) => (
                  <label key={optIdx} className="flex items-center gap-3 p-3 rounded-lg border border-zinc-800/50 bg-zinc-900/40 cursor-pointer hover:bg-zinc-800/40 transition">
                    <input
                      type="radio"
                      name={`question-${idx}`}
                      value={opt}
                      checked={answers[idx] === opt}
                      onChange={() => setAnswers({...answers, [idx]: opt})}
                      disabled={score !== null}
                      className="text-amber-500 focus:ring-amber-500"
                    />
                    <span className="text-sm text-zinc-300">{opt}</span>
                  </label>
                ))}
              </div>
              {score !== null && (
                <div className={`p-4 rounded-xl text-sm ${answers[idx] === q.correct_answer ? 'bg-green-500/10 border-green-500/20 text-green-400' : 'bg-red-500/10 border-red-500/20 text-red-400'}`}>
                  <p className="font-bold flex items-center gap-2">
                    {answers[idx] === q.correct_answer ? <CheckCircle2 size={16}/> : <AlertTriangle size={16}/>}
                    {answers[idx] === q.correct_answer ? "Correct!" : `Incorrect. Correct Answer: ${q.correct_answer}`}
                  </p>
                  <p className="mt-2 text-zinc-400">{q.explanation}</p>
                </div>
              )}
            </div>
          ))}

          {score === null ? (
            <button
              onClick={handleSubmit}
              className="w-full bg-amber-600 hover:bg-amber-500 text-white font-bold py-3 rounded-xl transition"
            >
              Submit Answers
            </button>
          ) : (
            <div className="text-center space-y-4">
              <h3 className="text-2xl font-bold text-white">Your Score: {score}%</h3>
              <button
                onClick={handleGenerate}
                disabled={generating}
                className="text-amber-400 hover:text-amber-300 text-sm font-semibold transition"
              >
                Generate New Test
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
